reactor:
  servicePort: 7778
  membershipPort: 4801
  seeds:
    - seed-service:4801

logLevel: INFO

entityProvider: com.ustack.service.dynamodb.DynamodbEntityProvider
leadershipProvider: com.ustack.service.dynamodb.DynamodbLeadershipProvider
keyRoutingProvider: com.ustack.service.dynamodb.DynamodbKeyRoutingProvider

zones:
  seed_v2:
    reactor:
      seeds: []
  lb_v2:
    functions:
      - name: lb
        func: com.ustack.service.KeyLoadBalancer
        router: LEADER_BASED
  web_v2:
    webApi:
      host: 0.0.0.0
      port: 8080
    websocket:
      host: 0.0.0.0
      port: 8000
  fplp_v2:
    providers:
      - provider: com.ust.ats.StockLoanDeskService
    functions:
      - name: firstGenBridge
        func: com.ust.ats.bridge.service.BridgeService
        router: SERVICE_ID
  splitter_v2:
    providers:
      - provider: com.ust.ats.StockLoanSplitterService
    functions:
      - name: firstGenBridge
        func: com.ust.ats.bridge.service.BridgeService
        router: SERVICE_ID
  common_v2:
    providers:
      - provider: com.ustack.service.configservice.ConfigService
      - provider: com.ust.ats.CalendarService
      - provider: com.ust.ats.ReportGenService
      - provider: com.ustack.service.filemanager.FileManagerService
    functions:
      - name: firstGenBridge
        func: com.ust.ats.bridge.service.BridgeService
        router: SERVICE_ID
  db_v2:
    providers:
      - provider: com.ustack.service.genericquery.GenericQueryService
    functions:
      - name: SqlReplicator
        func: com.ustack.service.sqlreplicator.SqlReplicator
        router: LEADER_BASED
  static_v2:
    providers:
      - provider: com.ust.ats.FTPService
      - provider: com.ust.ats.banking.service.BankingService
    functions:
      - name: firstGenBridge
        func: com.ust.ats.bridge.service.BridgeService
        router: SERVICE_ID
  control_v2:
    functions:
      - name: appCoordinator
        func: com.ustack.app.ReactorAppCoordinator
        router: ROUND_ROBIN
      - name: reactorAppQueryService
        func: com.ustack.app.ReactorAppQueryService
        router: ROUND_ROBIN
      - name: statCollector
        func: com.ustack.app.ReactorAppStatCollector
        router: ROUND_ROBIN
env:
  ENV_NAME: ${{ env.ENV_NAME }}
  PGSQL_HOST: ${{ control.PGSQL_HOST }}
  PGSQL_USERNAME: ${{ control.PGSQL_USERNAME }}
  PGSQL_PASSWORD: ${{ control.PGSQL_PASSWORD }}
  CONTROL_TABLE: control
  DEFAULT_PERSISTED_TABLE: default_persisted
  DEFAULT_STREAM_TABLE: default_stream
  DEFAULT_SNAPSHOT_TABLE: default_snapshot
  LEADERSHIP_HB_INTERVAL: 30
  LEADERSHIP_CHECK_INTERVAL: 5
  LEADERSHIP_MAX_RETRIES: 5
  SCHEMA_DIRECTORY: ./app/schema