name: UATS docker build workflow
on: [push]
jobs:
  build:
    name: Build UATS microservice image
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    env:
      BUILD_VERSION: ${{ github.event.head_commit.message }} # Change this for main branch
      BUILD_ARTIFACT_TYPE: ${{ secrets.BUILD_ARTIFACT_TYPE }}
      BUILD_ARTIFACT_LOACTION: ${{ secrets.BUILD_ARTIFACT_LOACTION }}
    steps:
      - name: Get Branch Details
        uses: rlespinasse/github-slug-action@v3.x
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ECR_AWS_REGION }}
      - name: Download Artifacts to Repocitory
        run: |
          aws s3 cp \
            "$BUILD_ARTIFACT_LOACTION/$BUILD_ARTIFACT_TYPE/$BUILD_VERSION/$BUILD_ARTIFACT_TYPE-$BUILD_VERSION.tar.gz" \
            artifacts.tar.gz >> /dev/null
          tar -xvzf artifacts.tar.gz
          rm -f artifacts.tar.gz
          tree
      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build image and push to ECR
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$BUILD_ARTIFACT_TYPE:$BUILD_VERSION .
          docker push $ECR_REGISTRY/$BUILD_ARTIFACT_TYPE:$BUILD_VERSION